<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="PdfSharp.MigraDoc.Standard" Version="1.51.15" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IvanSusaninProject_Contracts\IvanSusaninProject_Contracts.csproj" />
    <ProjectReference Include="..\IvanSusaninProject_Database\IvanSusaninProject_DataBase.csproj" />
  </ItemGroup>

</Project>
