// <auto-generated />
using System;
using IvanSusaninProject_Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IvanSusaninProject_DataBase.Migrations
{
    [DbContext(typeof(IvanSusaninProject_DbContext))]
    [Migration("20250820123836_NullableGroupId")]
    partial class NullableGroupId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Guide", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fio")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Place", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EndCity")
                        .HasColumnType("text");

                    b.Property<string>("StartCity")
                        .HasColumnType("text");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.TripGuide", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text");

                    b.Property<string>("GuideId")
                        .HasColumnType("text");

                    b.HasKey("TripId", "GuideId");

                    b.HasIndex("GuideId");

                    b.ToTable("TripGuides");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.TripPlace", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.HasKey("TripId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("TripPlaces");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login", "PasswordHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Excursion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExcursionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GuideId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Excursions");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("HumanAmount")
                        .HasColumnType("integer");

                    b.Property<int>("HumanType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Tour", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.TourExcursion", b =>
                {
                    b.Property<string>("TourId")
                        .HasColumnType("text");

                    b.Property<string>("ExcursionId")
                        .HasColumnType("text");

                    b.HasKey("TourId", "ExcursionId");

                    b.HasIndex("ExcursionId");

                    b.ToTable("TourExcursions");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.TourGroup", b =>
                {
                    b.Property<string>("TourId")
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.HasKey("TourId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("TourGroups");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Guide", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Place", b =>
                {
                    b.HasOne("IvanSusaninProject_Database.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Trip", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.TripGuide", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.Guide", null)
                        .WithMany("TripGuides")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanSusaninProject_DataBase.Models.Trip", null)
                        .WithMany("TripGuides")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.TripPlace", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.Place", null)
                        .WithMany("TripPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanSusaninProject_DataBase.Models.Trip", null)
                        .WithMany("TripPlaces")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Excursion", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.Guide", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId");

                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Group", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Tour", b =>
                {
                    b.HasOne("IvanSusaninProject_DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.TourExcursion", b =>
                {
                    b.HasOne("IvanSusaninProject_Database.Models.Excursion", "Excursion")
                        .WithMany("TourExcursions")
                        .HasForeignKey("ExcursionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanSusaninProject_Database.Models.Tour", "Tour")
                        .WithMany("TourExcursions")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excursion");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.TourGroup", b =>
                {
                    b.HasOne("IvanSusaninProject_Database.Models.Group", "Group")
                        .WithMany("TourGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanSusaninProject_Database.Models.Tour", "Tour")
                        .WithMany("TourGroups")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Guide", b =>
                {
                    b.Navigation("TripGuides");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Place", b =>
                {
                    b.Navigation("TripPlaces");
                });

            modelBuilder.Entity("IvanSusaninProject_DataBase.Models.Trip", b =>
                {
                    b.Navigation("TripGuides");

                    b.Navigation("TripPlaces");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Excursion", b =>
                {
                    b.Navigation("TourExcursions");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Group", b =>
                {
                    b.Navigation("TourGroups");
                });

            modelBuilder.Entity("IvanSusaninProject_Database.Models.Tour", b =>
                {
                    b.Navigation("TourExcursions");

                    b.Navigation("TourGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
